# Generated by Django 2.2.2 on 2019-10-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=3000)),
                ('pub_date', models.DateField()),
                ('image_url', models.CharField(max_length=500)),
                ('product_url', models.CharField(max_length=500)),
                ('Brand', models.CharField(max_length=500)),
                ('Model', models.CharField(max_length=500)),
                ('Model_Name', models.CharField(max_length=500)),
                ('Model_Year', models.CharField(max_length=500)),
                ('Item_Weight', models.CharField(max_length=500)),
                ('Product_Dimensions', models.CharField(max_length=500)),
                ('Batteries', models.CharField(max_length=500)),
                ('Item_model', models.CharField(max_length=500)),
                ('Compatible_Devices', models.CharField(max_length=500)),
                ('Additional_Features', models.CharField(max_length=500)),
                ('Included_Components', models.CharField(max_length=500)),
            ],
        ),
    ]
